In [1]:
import wfdb, time
import numpy as np
from utils import *

In [ ]:
patient_files = [
            ('C:/Users/anany/Downloads/slp32', 'C:/Users/anany/Downloads/slp32.st'),
            ('C:/Users/anany/Downloads/slp37', 'C:/Users/anany/Downloads/slp37.st'),
            ('C:/Users/anany/Downloads/slp41', 'C:/Users/anany/Downloads/slp41.st'),
            ('C:/Users/anany/Downloads/slp45', 'C:/Users/anany/Downloads/slp45.st'),
            ('C:/Users/anany/Downloads/slp48', 'C:/Users/anany/Downloads/slp48.st')
        ]

combined_signals = []
combined_labels = []

for dat_file, st_file in patient_files:
    record = wfdb.rdrecord(dat_file)  
    annotations = wfdb.rdann(dat_file, 'st')  

    signals = record.p_signal  
    fs = record.fs  
    signal_names = record.sig_name  

    aux_notes = annotations.aux_note  # Sleep stage and apnea annotations
    annotation_times = annotations.sample  # Annotation times (in samples)

    stage_mapping = {
        'W': 0,  # Wake
        '1': 1,  # NREM1
        '2': 1,  # NREM2
        '3': 1,  # NREM3
        '4': 1,  # NREM3 (combined with stage 3)
        'R': 1   # REM
    }

    sleep_stages = []
    for aux in aux_notes:
        stage = aux.strip()  
        if stage in stage_mapping:  # Check if the stage is in the mapping
            sleep_stages.append(stage_mapping[stage])

    total_samples = len(sleep_stages) * fs * 30  
    signals = [signal[:total_samples] for signal in signals.T] 
    signals = np.array(signals)  

    combined_signals.append(signals)
    combined_labels.extend(sleep_stages)

combined_signals = np.concatenate(combined_signals, axis=1)  
combined_labels = np.array(combined_labels)  
print("Combined signals shape:", combined_signals.shape)
print("Combined labels shape:", combined_labels.shape)
print("Sampling frequency:", fs)

main_pipeline(combined_signals, combined_labels, fs, "binary")

Combined signals shape: (7, 8295000)
Combined labels shape: (1106,)
Sampling frequency: 250
Preprocessing signals...
Preprocessed signals shape: (7, 8295000)
Preprocessing completed.
Segmentation started...
Segmented signals shape: (1106, 52500)
Number of labels: 1106
Feature extraction started...
Extracting features...
Ensuring consistent feature dimensions...
Number of feature dictionaries: 1106
Feature extraction completed.
Normalizing features...
Number of normalized feature dictionaries: 1106
Feature normalization completed.
Converting features to matrix...
Feature matrix shape: (1106, 151)
Feature conversion completed.
Filtering features based on mutual information...
Feature filtering completed.
Performing mRMR feature selection...
mRMR feature selection completed.
Training and evaluating SVM...
Training SVM...
SVM training completed in 0.01 seconds.
Evaluating SVM...
Confusion Matrix:
[[109  20]
 [ 47  46]]

Classification Report:
              precision    recall  f1-score   s

In [ ]:
patient_files = [
            ('C:/Users/anany/Downloads/slp32', 'C:/Users/anany/Downloads/slp32.st')
        ]

combined_signals = []
combined_labels = []

for dat_file, st_file in patient_files:
    record = wfdb.rdrecord(dat_file)  
    annotations = wfdb.rdann(dat_file, 'st')  

    signals = record.p_signal  
    fs = record.fs  
    signal_names = record.sig_name  

    aux_notes = annotations.aux_note  
    annotation_times = annotations.sample  

    stage_mapping = {
        'W': 0,  # Wake
        '1': 1,  # NREM1
        '2': 1,  # NREM2
        '3': 1,  # NREM3
        '4': 1,  # NREM3 (combined with stage 3)
        'R': 1   # REM
    }

    sleep_stages = []
    for aux in aux_notes:
        stage = aux.strip() 
        if stage in stage_mapping:  
            sleep_stages.append(stage_mapping[stage])

    total_samples = len(sleep_stages) * fs * 30  
    signals = [signal[:total_samples] for signal in signals.T]  
    signals = np.array(signals) 

    combined_signals.append(signals)
    combined_labels.extend(sleep_stages)

combined_signals = np.concatenate(combined_signals, axis=1)  
combined_labels = np.array(combined_labels) 
print("Combined signals shape:", combined_signals.shape)
print("Combined labels shape:", combined_labels.shape)
print("Sampling frequency:", fs)

main_pipeline(combined_signals, combined_labels, fs, "binary")

Combined signals shape: (7, 3825000)
Combined labels shape: (510,)
Sampling frequency: 250
Preprocessing signals...
Preprocessed signals shape: (7, 3825000)
Preprocessing completed.
Segmentation started...
Segmented signals shape: (510, 52500)
Number of labels: 510
Feature extraction started...
Extracting features...
Ensuring consistent feature dimensions...
Number of feature dictionaries: 510
Feature extraction completed.
Normalizing features...
Number of normalized feature dictionaries: 510
Feature normalization completed.
Converting features to matrix...
Feature matrix shape: (510, 151)
Feature conversion completed.
Filtering features based on mutual information...
Feature filtering completed.
Performing mRMR feature selection...
mRMR feature selection completed.
Training and evaluating SVM...
Training SVM...
SVM training completed in 0.00 seconds.
Evaluating SVM...
Confusion Matrix:
[[77  0]
 [17  8]]

Classification Report:
              precision    recall  f1-score   support

  

In [ ]:
patient_files = [
            ('C:/Users/anany/Downloads/slp32', 'C:/Users/anany/Downloads/slp32.st'),
            ('C:/Users/anany/Downloads/slp37', 'C:/Users/anany/Downloads/slp37.st'),
            ('C:/Users/anany/Downloads/slp41', 'C:/Users/anany/Downloads/slp41.st'),
            ('C:/Users/anany/Downloads/slp45', 'C:/Users/anany/Downloads/slp45.st'),
            ('C:/Users/anany/Downloads/slp48', 'C:/Users/anany/Downloads/slp48.st')
        ]

combined_signals = []
combined_labels = []

for dat_file, st_file in patient_files:
    record = wfdb.rdrecord(dat_file)  
    annotations = wfdb.rdann(dat_file, 'st')  

    signals = record.p_signal  
    fs = record.fs 
    signal_names = record.sig_name  

    aux_notes = annotations.aux_note  
    annotation_times = annotations.sample  

    stage_mapping = {
        'W': 0,  # Wake
        '1': 1,  # NREM1
        '2': 2,  # NREM2
        '3': 3,  # NREM3
        '4': 3,  # NREM3 (combined with stage 3)
        'R': 4   # REM
    }

    sleep_stages = []
    for aux in aux_notes:
        stage = aux.strip()  
        if stage in stage_mapping:  
            sleep_stages.append(stage_mapping[stage])

    total_samples = len(sleep_stages) * fs * 30  
    signals = [signal[:total_samples] for signal in signals.T] 
    signals = np.array(signals) 

    combined_signals.append(signals)
    combined_labels.extend(sleep_stages)

combined_signals = np.concatenate(combined_signals, axis=1)  
combined_labels = np.array(combined_labels)  

print("Combined signals shape:", combined_signals.shape)
print("Combined labels shape:", combined_labels.shape)
print("Sampling frequency:", fs)

main_pipeline(combined_signals, combined_labels, fs, "multiclass")


Combined signals shape: (7, 8295000)
Combined labels shape: (1106,)
Sampling frequency: 250
Preprocessing signals...
Preprocessed signals shape: (7, 8295000)
Preprocessing completed.
Segmentation started...
Segmented signals shape: (1106, 52500)
Number of labels: 1106
Feature extraction started...
Extracting features...
Ensuring consistent feature dimensions...
Number of feature dictionaries: 1106
Feature extraction completed.
Normalizing features...
Number of normalized feature dictionaries: 1106
Feature normalization completed.
Converting features to matrix...
Feature matrix shape: (1106, 151)
Feature conversion completed.
Filtering features based on mutual information...
Feature filtering completed.
Performing mRMR feature selection...
mRMR feature selection completed.
Training and evaluating SVM...
Training SVM...
SVM training completed in 0.02 seconds.
Evaluating SVM...
Confusion Matrix:
[[128   0   1   0   0]
 [ 14   0   6   0   1]
 [ 43   0  16   0   1]
 [  4   0   2   0   0]
 [

c:\Users\anany\Desktop\OSA\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anany\Desktop\OSA\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anany\Desktop\OSA\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
patient_files = [
            ('C:/Users/anany/Downloads/slp32', 'C:/Users/anany/Downloads/slp32.st')
        ]

combined_signals = []
combined_labels = []

for dat_file, st_file in patient_files:
    record = wfdb.rdrecord(dat_file)  
    annotations = wfdb.rdann(dat_file, 'st') 

    signals = record.p_signal  
    fs = record.fs  
    signal_names = record.sig_name  

    aux_notes = annotations.aux_note 
    annotation_times = annotations.sample  

    stage_mapping = {
        'W': 0,  # Wake
        '1': 1,  # NREM1
        '2': 2,  # NREM2
        '3': 3,  # NREM3
        '4': 3,  # NREM3 (combined with stage 3)
        'R': 4   # REM
    }

    sleep_stages = []
    for aux in aux_notes:
        stage = aux.strip()  
        if stage in stage_mapping:  
            sleep_stages.append(stage_mapping[stage])

    total_samples = len(sleep_stages) * fs * 30  
    signals = [signal[:total_samples] for signal in signals.T]  
    signals = np.array(signals)  

    combined_signals.append(signals)
    combined_labels.extend(sleep_stages)

combined_signals = np.concatenate(combined_signals, axis=1)  
combined_labels = np.array(combined_labels)  

print("Combined signals shape:", combined_signals.shape)
print("Combined labels shape:", combined_labels.shape)
print("Sampling frequency:", fs)

main_pipeline(combined_signals, combined_labels, fs, "multiclass")


Combined signals shape: (7, 3825000)
Combined labels shape: (510,)
Sampling frequency: 250
Preprocessing signals...
Preprocessed signals shape: (7, 3825000)
Preprocessing completed.
Segmentation started...
Segmented signals shape: (510, 52500)
Number of labels: 510
Feature extraction started...
Extracting features...
Ensuring consistent feature dimensions...
Number of feature dictionaries: 510
Feature extraction completed.
Normalizing features...
Number of normalized feature dictionaries: 510
Feature normalization completed.
Converting features to matrix...
Feature matrix shape: (510, 151)
Feature conversion completed.
Filtering features based on mutual information...
Feature filtering completed.
Performing mRMR feature selection...
mRMR feature selection completed.
Training and evaluating SVM...
Training SVM...
SVM training completed in 0.01 seconds.
Evaluating SVM...
Confusion Matrix:
[[77  0  0  0]
 [ 3  0  0  0]
 [12  0  4  0]
 [ 5  0  1  0]]

Classification Report:
              p

c:\Users\anany\Desktop\OSA\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anany\Desktop\OSA\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anany\Desktop\OSA\env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
